import Head from "next/head";
import Qrcode from "../components/Qrcode";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="app bg-slate-100 h-screen w-screen justify-center flex">
        <Qrcode />
      </main>
    </>
  );
}
